### ISSUE TITLE
Creating new window

### ISSUE THREAD

**Issue by nthtson** [prdlab/wrappy-desktop#5]
- Apply new api_id and api_hash. (ref: https://core.telegram.org/api/obtaining_api_id)
- Add more menu item with name "My Page" (under New Channel), open new window when click to it.
- On new window, please display Telegram user_id, phone and username.

**Comment by phuongchuyentin** [comment]
Note: 
+ Debug project on qt creator : 
Select project Wrappy => Debug => Start Debugging => Start Debugging Without Deployment:
Commandline arguments: input  -DCMAKE_BUILD_TYPE=Debug .

+ Build project: Build => select "Build Without Deployment."

**Comment by nthtson** [comment]
This issue was moved to prdlab/wrappy-desktop#5
